name: learn_flutter_step_by_step
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2023.05.02+20230502

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  #https://pub.dev/packages/get
  get: ^4.6.5
  #https://pub.dev/packages/intl
  intl: ^0.18.1
  #https://pub.dev/packages/logger
  logger: ^1.3.0
  #https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.1.1
  #https://pub.dev/packages/shimmer
  shimmer: ^2.0.0
  #https://pub.dev/packages/package_info_plus
  package_info_plus: ^3.1.2
  #https://pub.dev/packages/avatar_glow
  avatar_glow: ^2.0.2
  #https://pub.dev/packages/in_app_review
  in_app_review: ^2.0.6
  #https://pub.dev/packages/url_launcher
  url_launcher: ^6.1.11
  #https://pub.dev/packages/animated_text_kit
  animated_text_kit: ^4.2.2
  #https://pub.dev/packages/animated_toggle_switch
  animated_toggle_switch: ^0.6.2
  #https://pub.dev/packages/auto_size_text
  auto_size_text: ^3.0.0
  #https://pub.dev/packages/app_settings
  app_settings: ^4.2.0
  #https://pub.dev/packages/blur
  blur: ^3.1.0
  #https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.2.3
  #https://pub.dev/packages/carousel_slider
  carousel_slider: ^4.2.1
  #https://pub.dev/packages/clipboard
  clipboard: ^0.1.3
  #https://pub.dev/packages/confetti
  confetti: ^0.7.0
  #https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^3.0.3
  #https://pub.dev/packages/device_info_plus
  device_info_plus: ^8.1.0
  #https://pub.dev/packages/dio
  dio: ^5.1.2
  #https://pub.dev/packages/dotted_border
  dotted_border: ^2.0.0+3
  #https://pub.dev/packages/dotted_line
  dotted_line: ^3.1.0
  #https://pub.dev/packages/easy_debounce
  easy_debounce: ^2.0.3
  #https://pub.dev/packages/event_bus
  event_bus: ^2.0.0
  #https://pub.dev/packages/focus_detector
  focus_detector: ^2.0.1
  #https://pub:dev/packages/file_picker
  file_picker: ^5.2.6
  #https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^3.0.5
  #https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: ^9.9.1 #migrate later
  #https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.2.19
  #https://pub.dev/packages/flutter_rounded_date_picker
  flutter_rounded_date_picker: ^3.0.2
  #https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.1.6 #migrate later
  #https://pub.dev/packages/flutter_phoenix
  flutter_phoenix: ^1.1.1
  #https://pub.dev/packages/hexcolor
  hexcolor: ^3.0.1
  #https://pub.dev/packages/lottie
  lottie: ^2.3.2
  #https://pub.dev/packages/scrollable_positioned_list
  scrollable_positioned_list: ^0.3.5
  #https://pub.dev/packages/share_plus
  share_plus: ^6.3.1
  #https://pub.dev/packages/marquee
  marquee: ^2.2.3
  #https://pub.dev/packages/rxdart
  rxdart: ^0.27.7
  #https://pub.dev/packages/image_gallery_saver
  image_gallery_saver: ^1.7.1
  #https://pub.dev/packages/image_picker
  image_picker: ^0.8.7
  #https://pub.dev/packages/kenburns_nullsafety
  kenburns_nullsafety: ^1.0.0
  #https://pub.dev/packages/path_provider
  path_provider: ^2.0.13
  #https://pub.dev/packages/permission_handler
  permission_handler: ^10.2.0
  #https://pub.dev/packages/photo_view
  photo_view: ^0.14.0
  #https://pub.dev/packages/platform_device_id
  platform_device_id: ^1.0.1
  #https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  #https://pub.dev/packages/shape_of_view_null_safe
  shape_of_view_null_safe: ^2.0.0
  #https://pub.dev/packages/sliding_up_panel
  sliding_up_panel: ^2.0.0+1
  #https://pub.dev/packages/tiengviet
  tiengviet: ^0.5.0
  #https://pub.dev/packages/timeago
  timeago: ^3.4.0
  #https://pub.dev/packages/uuid
  uuid: ^3.0.7
  #https://pub.dev/packages/vibration
  vibration: ^1.7.7
  #https://pub.dev/packages/webview_flutter
  webview_flutter: ^4.2.0
  #https://pub.dev/packages/youtube_player_flutter
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  #https://pub.dev/packages/flutter_launcher_icons
  #flutter_launcher_icons: "^0.10.0"

  #https://pub.dev/packages/flutter_app_name
  #flutter_app_name: ^0.1.1
  #name: "Flutter tutorials"

  #change_app_package_name: ^1.1.0

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/coding.png"
#  flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
#  fonts:
#    - family: Pacifico
#      fonts:
#        - asset: data_repo/fonts/Pacifico-Regular.ttf
#          weight: 400
  assets:
    - assets/files/
    - assets/videos/
    - assets/images/
